spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.193.66:3306/t_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: AcoHikariCP # 连接池名称
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000

mybatis-plus:
  type-aliases-package: com.aco.pracitce.demo1.domain
  mapper-locations: classpath:mapper/*.xml
